---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
    - hosts:
        - nextcloud.localhost
      secretName: nextcloud-tls-certificate
    - hosts:
        - minio.localhost
      secretName: minio-tls-certificate
    - hosts:
        - n8n.localhost
      secretName: n8n-tls-certificate
    - hosts:
        - gotify.localhost
      secretName: gotify-tls-certificate
  rules:
    - host: nextcloud.localhost
      http:
        paths:
          - backend:
              service:
                name: nextcloud
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: minio.localhost
      http:
        paths:
          - backend:
              service:
                name: minio
                port:
                  number: 9000
            path: /
            pathType: Prefix
    - host: n8n.localhost
      http:
        paths:
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /
            pathType: Prefix
    - host: gotify.localhost
      http:
        paths:
          - backend:
              service:
                name: gotify
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: whoami.localhost
      http:
        paths:
          - backend:
              service:
                name: whoami
                port:
                  number: 80
            path: /
            pathType: Prefix
