---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - nextcloud.localhost
      secretName: nextcloud-tls-certificate
    - hosts:
        - minio.localhost
      secretName: minio-tls-certificate
    - hosts:
        - dashboard.minio.localhost
      secretName: dashboard-minio-tls-certificate
    - hosts:
        - n8n.localhost
      secretName: n8n-tls-certificate
    - hosts:
        - gotify.localhost
      secretName: gotify-tls-certificate
    - hosts:
        - kuma.localhost
      secretName: kuma-tls-certificate
  rules:
    - host: nextcloud.localhost
      http:
        paths:
          - backend:
              service:
                name: nextcloud
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: minio.localhost
      http:
        paths:
          - backend:
              service:
                name: minio
                port:
                  number: 9000
            path: /
            pathType: Prefix
    - host: dashboard.minio.localhost
      http:
        paths:
          - backend:
              service:
                name: dashboard-minio
                port:
                  number: 9001
            path: /
            pathType: Prefix
    - host: n8n.localhost
      http:
        paths:
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /
            pathType: Prefix
    - host: gotify.localhost
      http:
        paths:
          - backend:
              service:
                name: gotify
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: whoami.localhost
      http:
        paths:
          - backend:
              service:
                name: whoami
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: kuma.localhost
      http:
        paths:
          - backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
            path: /
            pathType: Prefix
