---
secretGenerator:
  - name: postgres-secret
    files:
      - username=.secrets/postgres-secret/username
      - password=.secrets/postgres-secret/password
  - name: restic-secret
    files:
      - access_key_id=.secrets/restic-secret/access_key_id
      - secret_access_key=.secrets/restic-secret/secret_access_key
      - password=.secrets/restic-secret/password
  - name: restic-staging-secret
    files:
      - access_key_id=.secrets/restic-staging-secret/access_key_id
      - secret_access_key=.secrets/restic-staging-secret/secret_access_key
      - password=.secrets/restic-staging-secret/password
  - name: minio-secret
    files:
      - access_key_id=.secrets/minio-secret/access_key_id
      - secret_access_key=.secrets/minio-secret/secret_access_key
  - name: n8n-secret
    files:
      - encryption=.secrets/n8n-secret/encryption
      - user=.secrets/n8n-secret/user
      - password=.secrets/n8n-secret/password
  - name: gotify-secret
    files:
      - user=.secrets/gotify-secret/user
      - password=.secrets/gotify-secret/password
configMapGenerator:
  - name: restic-config
    files:
      - repository=.secrets/restic-config/repository
  - name: restic-staging-config
    files:
      - repository=.secrets/restic-staging-config/repository
  - name: nextcloud-config
    behavior: merge  # nextcloud/config.yaml
    files:
      - nginx_conf=nextcloud/nginx.conf
  - name: wireguard-config
    files:
      - host=.secrets/wireguard-config/host
resources:
  - ingress.yaml
  - common/postgres.yaml
  - nextcloud/persistent-volume.yaml
  - nextcloud/config.yaml
  - nextcloud/restore.yaml
  - nextcloud/nextcloud.yaml
  - nextcloud/backup.yaml
  - minio/minio.yaml
  - n8n/n8n.yaml
  - gotify/gotify.yaml
  - whoami/whoami.yaml
  - wireguard/wireguard.yaml
patches:
  - .secrets/patches/ingress.yaml
  - nextcloud/patches/persistent-volume.yaml
  - nextcloud/patches/restore.yaml
  - nextcloud/patches/backup.yaml
  - minio/patches/persistent-volume.yaml
