---
secretGenerator:
  - name: postgres-secret
    files:
      - username=.secrets/postgres-secret/username
      - password=.secrets/postgres-secret/password
  - name: restic-secret
    files:
      - access_key_id=.secrets/restic-secret/access_key_id
      - secret_access_key=.secrets/restic-secret/secret_access_key
      - password=.secrets/restic-secret/password
  - name: restic-staging-secret
    files:
      - access_key_id=.secrets/restic-staging-secret/access_key_id
      - secret_access_key=.secrets/restic-staging-secret/secret_access_key
      - password=.secrets/restic-staging-secret/password
  - name: minio-secret
    files:
      - access_key_id=.secrets/minio-secret/access_key_id
      - secret_access_key=.secrets/minio-secret/secret_access_key
configMapGenerator:
  - name: restic-config
    files:
      - repository=.secrets/restic-config/repository
  - name: restic-staging-config
    files:
      - repository=.secrets/restic-staging-config/repository
resources:
  - ingress.yaml
  - common/postgres.yaml
  - nextcloud/persistent-volume.yaml
  - nextcloud/config.yaml
  - nextcloud/restore.yaml
  - nextcloud/nextcloud.yaml
  - nextcloud/backup.yaml
  - minio/minio.yaml
