---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pv-claim
  labels:
    app: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  ports:
    - port: 5678
  selector:
    app: n8n
  clusterIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - image: n8nio/n8n:1.51.2
          name: n8n
          env:
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_PORT
              value: "5678"
            - name: NODE_ENV
              value: production
            - name: GENERIC_TIMEZONE
              value: "Europe/Paris"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: user
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: password
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: encryption
          ports:
            - containerPort: 5678
              name: n8n
          volumeMounts:
            - name: n8n-persistent-storage
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-persistent-storage
          persistentVolumeClaim:
            claimName: n8n-pv-claim
