---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  ports:
    - port: 80
  selector:
    app: nextcloud
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - image: nextcloud:25.0.4-fpm
          name: nextcloud
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: db_authority
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: nextcloud-config
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: NEXTCLOUD_UPDATE
              value: "1"
          ports:
            - containerPort: 9000
              name: fpm
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
          command: ["/entrypoint.sh"]
          args: ["bash", "-c", "/cron.sh & php-fpm"]
        - image: nginx:1.23.3-alpine
          name: nginx
          ports:
            - containerPort: 80
              name: nginx
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
              readOnly: true
      volumes:
        - name: nextcloud-persistent-storage
          persistentVolumeClaim:
            claimName: nextcloud-pv-claim
        - name: nginx-conf
          configMap:
            name: nextcloud-config
            items:
              - key: nginx_conf
                path: nginx.conf
