---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kuma-proxy
  namespace: default
spec:
  virtualhost:
    fqdn: kuma.localhost
    tls:
      secretName: kuma-tls-certificate
  routes:
  - services:
    - name: uptime-kuma
      port: 3001
  - conditions:
    - prefix: /socket.io
    enableWebsockets: true
    services:
    - name: uptime-kuma
      port: 3001
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuma-tls-certificate
spec:
  commonName: kuma.localhost
  dnsNames:
  - kuma.localhost
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  secretName: kuma-tls-certificate
