---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pv-claim
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  ports:
    - port: 3001
  selector:
    app: uptime-kuma
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - image: louislam/uptime-kuma:1.23.0-alpine
          name: uptime-kuma
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: uptime-kuma-persistent-storage
              mountPath: /app/data
      volumes:
        - name: uptime-kuma-persistent-storage
          persistentVolumeClaim:
            claimName: uptime-kuma-pv-claim
