---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pv-claim
  labels:
    app: wireguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31820
      port: 51820
      protocol: UDP
      targetPort: 51820
  selector:
    app: wireguard
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wireguard
  name: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wireguard
      name: wireguard
    spec:
      containers:
        - image: ghcr.io/linuxserver/wireguard:legacy-v1.0.20210914-ls69
          name: wireguard
          securityContext:
            capabilities:
              add:
                - SYS_MODULE
                - NET_ADMIN
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
            - name: SERVERURL
              # value: "wireguard.localhost"
              valueFrom:
                configMapKeyRef:
                  name: wireguard-config
                  key: host
            - name: SERVERPORT
              value: "31820"
            - name: PEERS
              value: "sfos,wsl2"
          ports:
            - containerPort: 51820
              name: wireguard
          volumeMounts:
            - name: wireguard-persistent-storage
              mountPath: /config
              subPath: config
            - name: modules
              mountPath: /lib/modules
      volumes:
        - name: wireguard-persistent-storage
          persistentVolumeClaim:
            claimName: wireguard-pv-claim
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
