---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              env:
                - name: RESTIC_REPOSITORY
                  valueFrom:
                    configMapKeyRef:
                      name: restic-config
                      key: repository
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: restic-secret
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: restic-secret
                - name: RESTIC_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: restic-secret
                - name: POST_HOOK_URL
                  valueFrom:
                    configMapKeyRef:
                      name: restic-config
                      key: post_hook_url
